<a href="https://colab.research.google.com/github/AgacheM/Analyzing-Toronto-Airbnb-Dataset/blob/main/CIND_820_Notebook_1_Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Import Libraries**

In [35]:
#Import Libraries
#Exploratory Data Analysis
import pandas as pd

#Format without scientific notation
pd.options.display.float_format = '{:,.0f}'.format

#Formatting
from IPython.display import display

# **2. Download Listings & Reviews Data from Insideairbnb.com**

In [36]:
#Import Listings file
url_1 = "https://data.insideairbnb.com/canada/on/toronto/2026-01-16/data/listings.csv.gz"
df_listings=pd.read_csv(url_1, compression='gzip', index_col='id')

In [37]:
#Summarize Listings Data #Summarize
print(f"""
DATASET OVERVIEW
----------------
Rows: {df_listings.shape[0]:,}
Columns: {df_listings.shape[1]}
""")

print(f"""
FIRST 5 ROWS
---------------""")
display(df_listings.head())

DATASET OVERVIEW
----------------
Rows: 15,776
Columns: 84


FIRST 5 ROWS
---------------

,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
44452,https://www.airbnb.com/rooms/44452,20260116041757,2026-01-17,city scrape,Yonge & Bloor Studio Skyline,NaN,NaN,https://a0.muscache.com/pictures/395bd5b5-795a...,195095,https://www.airbnb.com/users/show/195095,...,5,5,4,NaN,NaN,13,10,3,0,0
44469,https://www.airbnb.com/rooms/44469,20260116041757,2026-01-16,city scrape,Yonge & Bloor 2 Bedroom Apartment,NaN,NaN,https://a0.muscache.com/pictures/250462/fa72a3...,195095,https://www.airbnb.com/users/show/195095,...,5,5,4,NaN,NaN,13,10,3,0,0
45399,https://www.airbnb.com/rooms/45399,20260116041757,2026-01-16,city scrape,Fountain View Studio - Eaton center,"Open Space studio style, Big windows, calm & r...",NaN,https://a0.muscache.com/pictures/5e2bfbce-c070...,195095,https://www.airbnb.com/users/show/195095,...,5,5,4,NaN,NaN,13,10,3,0,0
45893,https://www.airbnb.com/rooms/45893,20260116041757,2026-01-17,city scrape,Yonge & Bloor Lakeview Master BR,NaN,NaN,https://a0.muscache.com/pictures/29580691/baac...,195095,https://www.airbnb.com/users/show/195095,...,5,5,4,NaN,NaN,13,10,3,0,0
50110,https://www.airbnb.com/rooms/50110,20260116041757,2026-01-16,city scrape,Yorkville one bedroom Condo,Offering a great experience for guests staying...,NaN,https://a0.muscache.com/pictures/6329076e-ea60...,195095,https://www.airbnb.com/users/show/195095,...,5,5,4,NaN,NaN,13,10,3,0,0

In [38]:
#Data Types
print ("\n Data Types:")
display(df_listings.dtypes.to_frame(name="Type"))

print("\n Basic Statistics:")
display(df_listings.drop(columns=['listing_id'],errors='ignore').describe())

 Data Types:

                                                 Type
listing_url                                    object
scrape_id                                       int64
last_scraped                                   object
source                                         object
name                                           object
...                                               ...
calculated_host_listings_count                  int64
calculated_host_listings_count_entire_homes     int64
calculated_host_listings_count_private_rooms    int64
calculated_host_listings_count_shared_rooms     int64
reviews_per_month                             float64

[84 rows x 1 columns]

 Basic Statistics:

,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_response_time,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,"15,776",0,"15,776","15,775",0,"15,775","15,775","15,775","15,775",0,...,"12,545","12,545","12,545","12,545",0,"15,776","15,776","15,776","15,776","12,545"
mean,"20,260,116,041,757",NaN,"287,773,400","1,473,130,926,315,695,360",NaN,6,5,4,5,NaN,...,5,5,5,5,NaN,5,2,3,0,2
std,1,NaN,"245,812,991","22,187,876,805,309,136",NaN,4,3,4,3,NaN,...,0,0,0,0,NaN,12,4,11,0,2
min,"20,260,116,041,757",NaN,"28,515","1,462,507,096,808,142,592",NaN,0,0,0,0,NaN,...,1,1,1,1,NaN,1,0,0,0,0
25%,"20,260,116,041,757",NaN,"50,610,213","1,463,734,770,703,201,792",NaN,2,3,1,2,NaN,...,5,5,5,5,NaN,1,1,0,0,0
50%,"20,260,116,041,757",NaN,"211,875,892","1,468,694,370,696,296,960",NaN,7,5,3,5,NaN,...,5,5,5,5,NaN,1,1,0,0,1
75%,"20,260,116,041,757",NaN,"510,112,218","1,470,304,530,904,144,896",NaN,10,8,7,8,NaN,...,5,5,5,5,NaN,3,1,2,0,2
max,"20,260,116,041,757",NaN,"740,052,732","1,598,593,669,230,049,536",NaN,16,11,15,11,NaN,...,5,5,5,5,NaN,115,35,113,6,36

In [39]:
#Calculate Missing Values
print ("Missing Values:")
missing = df_listings.isnull().sum()
missing = missing[missing>0]

missing_percent=(missing/len(df_listings))*100

missing_summary = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent
})

#View only columns with missing values
missing_summary = missing_summary[missing_summary["Missing Count"]>0]

#Correct Errors
if len(missing_summary) > 0:
    display(
        missing_summary
        .sort_values (by="Missing %", ascending= False)
        .style.format({
            "Missing Count": "{:,.0f}",
            "Missing %": "{:.2f}%"
        })
        .background_gradient(cmap="Reds")
    )
else:
    print ("No Missing Values Found")

Missing Values:

In [40]:
#Handle the missing valules
#Drop columns with >50% missing values
columns_to_drop = missing_summary[missing_summary["Missing %"]>50].index
df_listings = df_listings.drop(columns=columns_to_drop)

print(f"Dropped {len(columns_to_drop)} columns with high missing values.")
print("Columns to Drop:")
print(columns_to_drop)

print ("Missing Values:")
missing = df_listings.isnull().sum()
missing = missing[missing>0]

missing_percent=(missing/len(df_listings))*100

missing_summary = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent
})

#View only columns with missing values
missing_summary = missing_summary[missing_summary["Missing Count"]>0]

#Correct Errors
if len(missing_summary) > 0:
    display(
        missing_summary
        .sort_values (by="Missing %", ascending= False)
        .style.format({
            "Missing Count": "{:,.0f}",
            "Missing %": "{:.2f}%"
        })
        .background_gradient(cmap="Reds")
    )
else:
    print ("No Missing Values Found")

Dropped 16 columns with high missing values.
Columns to Drop:
Index(['neighborhood_overview', 'host_since', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_thumbnail_url', 'host_neighbourhood', 'host_total_listings_count',
       'host_verifications', 'neighbourhood', 'neighbourhood_group_cleansed',
       'price', 'calendar_updated', 'estimated_revenue_l365d',
       'instant_bookable'],
      dtype='object')
Missing Values: